<a href="https://colab.research.google.com/github/zaidseliya0651-commits/231A050-NLP-Experiments/blob/main/AIDS_Sem7_NLP_Experiment08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Name: Zaid Seliya UIN: 231A050")
documents = [
    "The cat is sleeping on the sofa.",
    "The dog is playing in the garden.",
    "She is reading a book about science.",
    "The weather is sunny and pleasant today.",
    "The cat is playing with a small ball.",
    "He enjoys reading books in his free time.",
    "The children are playing in the garden.",
    "Machine learning helps computers understand language."
]

Name: Zaid Seliya UIN: 231A050

In [2]:
print("Name: Zaid Seliya UIN: 231A050")
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

Name: Zaid Seliya UIN: 231A050

In [3]:
print("Name: Zaid Seliya UIN: 231A050")
for i , document in enumerate(documents):
  print(f"D{i+1}: {document}")

Name: Zaid Seliya UIN: 231A050
D1: The cat is sleeping on the sofa.
D2: The dog is playing in the garden.
D3: She is reading a book about science.
D4: The weather is sunny and pleasant today.
D5: The cat is playing with a small ball.
D6: He enjoys reading books in his free time.
D7: The children are playing in the garden.
D8: Machine learning helps computers understand language.

In [4]:
print("Name: Zaid Seliya UIN: 231A050")
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)
print(tfidf_matrix.shape)

Name: Zaid Seliya UIN: 231A050
(8, 26)

In [5]:
print("Name: Zaid Seliya UIN: 231A050")
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=["D1","D2","D3","D4","D5","D6","D7","D8"]
    )
tfidf_df.round(2)

Name: Zaid Seliya UIN: 231A050

,ball,book,books,cat,children,computers,dog,enjoys,free,garden,...,reading,science,sleeping,small,sofa,sunny,time,today,understand,weather
D1,0.00,0.00,0.00,0.51,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.61,0.00,0.61,0.0,0.00,0.0,0.00,0.0
D2,0.00,0.00,0.00,0.00,0.00,0.00,0.67,0.00,0.00,0.56,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0
D3,0.00,0.61,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.51,0.61,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0
D4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.5,0.00,0.5,0.00,0.5
D5,0.56,0.00,0.00,0.47,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.56,0.00,0.0,0.00,0.0,0.00,0.0
D6,0.00,0.00,0.46,0.00,0.00,0.00,0.00,0.46,0.46,0.00,...,0.39,0.00,0.00,0.00,0.00,0.0,0.46,0.0,0.00,0.0
D7,0.00,0.00,0.00,0.00,0.67,0.00,0.00,0.00,0.00,0.56,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0
D8,0.00,0.00,0.00,0.00,0.00,0.41,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.41,0.0

In [6]:
print("Name: Zaid Seliya UIN: 231A050")
print(tfidf_matrix)

Name: Zaid Seliya UIN: 231A050
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 31 stored elements and shape (8, 26)>
  Coords	Values
  (0, 3)	0.5098138992318764
  (0, 18)	0.6083131546128155
  (0, 20)	0.6083131546128155
  (1, 6)	0.6703439317463478
  (1, 14)	0.48478776367676985
  (1, 9)	0.5618005316481324
  (2, 16)	0.5098138992318764
  (2, 1)	0.6083131546128155
  (2, 17)	0.6083131546128155
  (3, 25)	0.5
  (3, 21)	0.5
  (3, 15)	0.5
  (3, 23)	0.5
  (4, 3)	0.4666527853063489
  (4, 14)	0.40268306535511045
  (4, 19)	0.5568130417124039
  (4, 0)	0.5568130417124039
  (5, 16)	0.38647894810790673
  (5, 7)	0.46114911435169365
  (5, 2)	0.46114911435169365
  (5, 8)	0.46114911435169365
  (5, 22)	0.46114911435169365
  (6, 14)	0.48478776367676985
  (6, 9)	0.5618005316481324
  (6, 4)	0.6703439317463478
  (7, 13)	0.408248290463863
  (7, 12)	0.408248290463863
  (7, 10)	0.408248290463863
  (7, 5)	0.408248290463863
  (7, 24)	0.408248290463863
  (7, 11)	0.408248290463863

In [7]:
print("Name: Zaid Seliya UIN: 231A050")
print(vectorizer.get_feature_names_out())

Name: Zaid Seliya UIN: 231A050
['ball' 'book' 'books' 'cat' 'children' 'computers' 'dog' 'enjoys' 'free'
 'garden' 'helps' 'language' 'learning' 'machine' 'playing' 'pleasant'
 'reading' 'science' 'sleeping' 'small' 'sofa' 'sunny' 'time' 'today'
 'understand' 'weather']

In [8]:
print("Name: Zaid Seliya UIN: 231A050")
similarity_matrix = cosine_similarity(tfidf_matrix)
similarity_matrix

Name: Zaid Seliya UIN: 231A050

array([[1.        , 0.        , 0.        , 0.        , 0.23790608,
        0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.19521582,
        0.        , 0.55063901, 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.19703234, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.23790608, 0.19521582, 0.        , 0.        , 1.        ,
        0.        , 0.19521582, 0.        ],
       [0.        , 0.        , 0.19703234, 0.        , 0.        ,
        1.        , 0.        , 0.        ],
       [0.        , 0.55063901, 0.        , 0.        , 0.19521582,
        0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        ]])

In [9]:
print("Name: Zaid Seliya UIN: 231A050")
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=["D1","D2","D3","D4","D5","D6","D7","D8"],
    columns=["D1","D2","D3","D4","D5","D6","D7","D8"],
)
similarity_df.round(3)

Name: Zaid Seliya UIN: 231A050

       D1     D2     D3   D4     D5     D6     D7   D8
D1  1.000  0.000  0.000  0.0  0.238  0.000  0.000  0.0
D2  0.000  1.000  0.000  0.0  0.195  0.000  0.551  0.0
D3  0.000  0.000  1.000  0.0  0.000  0.197  0.000  0.0
D4  0.000  0.000  0.000  1.0  0.000  0.000  0.000  0.0
D5  0.238  0.195  0.000  0.0  1.000  0.000  0.195  0.0
D6  0.000  0.000  0.197  0.0  0.000  1.000  0.000  0.0
D7  0.000  0.551  0.000  0.0  0.195  0.000  1.000  0.0
D8  0.000  0.000  0.000  0.0  0.000  0.000  0.000  1.0

In [10]:
print("Name: Zaid Seliya UIN: 231A050")
print(similarity_matrix)

Name: Zaid Seliya UIN: 231A050
[[1.         0.         0.         0.         0.23790608 0.
  0.         0.        ]
 [0.         1.         0.         0.         0.19521582 0.
  0.55063901 0.        ]
 [0.         0.         1.         0.         0.         0.19703234
  0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.        ]
 [0.23790608 0.19521582 0.         0.         1.         0.
  0.19521582 0.        ]
 [0.         0.         0.19703234 0.         0.         1.
  0.         0.        ]
 [0.         0.55063901 0.         0.         0.19521582 0.
  1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.        ]]

In [11]:
print("Name: Zaid Seliya UIN: 231A050")
highest_similarity = -1
most_similar_pair = None

for i in range(len(documents)):
  for j in range (i + 1, len(documents)):
    similarity = similarity_matrix[i][j]
    if similarity > highest_similarity:
      highest_similarity = similarity
      most_similar_pair = (i,j)

print(
    f"Most Similar documents:"
    f"D{most_similar_pair[0] + 1} and D{most_similar_pair[1] + 1}"
)

print(f"Similarity : {highest_similarity:.3f}")

Name: Zaid Seliya UIN: 231A050
Most Similar documents:D2 and D7
Similarity : 0.551

In [12]:
print("Name: Zaid Seliya UIN: 231A050")
def similar(D1,D2):
  vector = vectorizer.fit_transform([D1,D2])
  similarity = cosine_similarity(vector)
  return similarity

Name: Zaid Seliya UIN: 231A050

In [13]:
print("Name: Zaid Seliya UIN: 231A050")
D9 = "The cat is resting on the sofa."
D10 = "She enjoys reading books about science."
similar(D9,D10)

Name: Zaid Seliya UIN: 231A050

array([[1., 0.],
       [0., 1.]])